version: '3.8'

services:
  starfish-test-task:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starfish-test-task
    image: image-starfish-test-task
    restart: on-failure
    depends_on:
      - postgres
    environment:
      SPRING_PROFILE: dev
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - starfish-test-task
  postgres:
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - starfish-test-task

volumes:
  postgres_data:

networks:
  starfish-test-task:
    driver: bridge
    name: starfish-test-task


